### ISSUE TITLE
lang++: error: the clang compiler does not support '-mfpu=neon-fp16'

### ISSUE THREAD

**Issue by ShevT** [TeamEOS/build#1]
Good day!

I am trying to collect TeamEOS for my phone.

At the beginning of the assembly I get the error:
clang++: error: the clang compiler does not support '-mfpu=neon-fp16'
My TARGET_CPU_VARIANT := cortex-a9

Here build/core/combo/arch/arm/armv7-a-neon.mk
...
ifneq (,$(filter cortex-a5 cortex-a9,$(TARGET_$(combo_2nd_arch_prefix)CPU_VARIANT)))
        arch_variant_cflags += -mfpu=neon-fp16
else
... 

Can you fix it so I collected TeamEOS for my phone?

**Comment by bigrushdog** [comment]
I'll forward this to the team for analysis. What device are you bringing up?

**Comment by raymanfx** [comment]
Hi @ShevT !
Please try this patch: http://review.teameos.org/#/c/347/.
It should remove the erroneous and unsupported fp16 flagging.

**Comment by ShevT** [comment]
I did so:
https://github.com/ShevT/build/commit/9ce599030e9bc68ec7bfcd746ff520ac4f8ee07f

**Comment by raymanfx** [comment]
The -fp16 switch is not supported currently so it should be removed completely (exactly what my patch does).
I can't really see what your changes are, please paste a well-formatted patch elsewhere.
It does however seem you didn't remove the -fp16 flag, which I said earlier needs to be removed anyways.
Please get my patch from Gerrit instead and see if it fixes your issue.

**Comment by ShevT** [comment]
Yes, your patch fixes the problem.
But the cortex-A9 need neon

peeped here: https://github.com/CyanogenMod/android_build/blob/cm-12.1/core/combo/arch/arm/armv7-a-neon.mk#L29

**Comment by raymanfx** [comment]
Yeah, that's exactly what my patch does.
By removing the cortex-a9 case, it falls through the if-condition and is handled by the else statement, which adds the neon flag.

**Comment by ShevT** [comment]
Yes. I totally agree.
Close ;)
